import { CharacterClass } from '../models/game.models';

export const WARLOCK: CharacterClass = {
  name: 'Warlock',
  color: '#8B2DF0',
  icon: '😈',
  iconImg: 'img/classes/warlock.jpg',

  formulas: {
    hp: (s, lvl) => 30 + s.aguante * 9 + lvl * 5,
    mana: (s, lvl) => 40 + s.intelecto * 18 + lvl * 6,
    spellPower: (s) => Math.round(s.intelecto * 0.45),
    attackPower: (s) => 0,
    manaRegen: (s) => Math.round(s.espiritu * 0.25 + 12),
  },

  baseStats: { fuerza: 10, agilidad: 10, intelecto: 16, aguante: 14, espiritu: 12 },
  startingLevel: 1,
  statGrowth: { intelecto: 2.0, aguante: 1.8, espiritu: 0.8, fuerza: 0.3, agilidad: 0.3 },
  armor: 5,
  magicResist: 3,

  resource: { type: 'mana', label: 'Mana', color: '#9b59b6', max: null, start: 'full' },

  comboConfig: { label: 'Soul Shards', icon: '🔮', max: 5 },

  talents: [
    { id: 'pocket_shards', name: 'Pocket Shards', icon: '🔮', iconImg: 'img/talents/warlock/pocket_shards.jpg', description: 'Tras un descanso mantienes 1 Soul Shard y aumentas tu maximo de Soul Shards en 1 por punto.', maxRank: 2, tier: 1, requires: null },
    { id: 'improved_drain_life', name: 'Improved Drain Life', icon: '🩸', iconImg: 'img/abilities/warlock/Spell_Shadow_LifeDrain02.jpg', description: 'Aumenta la vida que cura Drain Life un 10% por punto. Solo afecta a la curacion, no al dano.', maxRank: 3, tier: 1, requires: null },
    { id: 'demonic_embrace', name: 'Improved Soul Armor', icon: '😈', iconImg: 'img/talents/warlock/demonic_embrace.jpg', description: 'Mientras Fel Armor este activo, tu vida maxima aumenta un 10% por punto.', maxRank: 2, tier: 1, requires: null },
    { id: 'destruction_specialization', name: 'Destruction Specialization', icon: '💥', iconImg: '', description: 'Aumenta el dano de los golpes criticos de Chaos Bolt y Rain of Fire un 15% por punto.', maxRank: 3, tier: 1, requires: null },
    { id: 'dot_master', name: 'DoT Master', icon: '⏱️', iconImg: '', description: 'Aumenta la duracion de Corruption, Curse of Agony e Immolate en 1 turno por punto. El danyo por turno se mantiene igual, por lo que el total aumenta.', maxRank: 3, tier: 2, requires: null },
    { id: 'improved_healthstone', name: 'Improved Healthstone', icon: '💎', iconImg: 'img/abilities/warlock/INV_Stone_04.jpg', description: 'Aumenta la vida recuperada por Healthstone un 25% por punto. Si Healthstone cura a un aliado, tambien recuperas vida equivalente al 25% por punto de lo restaurado.', maxRank: 2, tier: 2, requires: null },
    { id: 'soul_conduit', name: 'Soul Conduit', icon: '🌀', iconImg: '', description: 'Al gastar Soul Shards en un hechizo o habilidad, tienes un 20% por punto de probabilidad de recuperar la Shard. Las invocaciones de demonios no se ven afectadas.', maxRank: 3, tier: 3, requires: null },
    { id: 'soul_leech', name: 'Soul Leech', icon: '🛡️', iconImg: '', description: 'Shadow Bolt y Chaos Bolt te otorgan un escudo equivalente al 5% por punto del dano infligido. El escudo se calcula sobre el dano final, incluidos los criticos.', maxRank: 2, tier: 3, requires: null },
  ],
  capstones: [
    { id: 'summon_infernal', name: 'Summon Infernal', icon: '🔥', iconImg: 'img/capstones/warlock/sumon_infernal.jpg', description: 'Coste: 2 Soul Shards. Invoca un Infernal desde el Twisting Nether. Al aterrizar, inflige daño de Fuego a todos los enemigos cercanos y los aturde durante 1 turno. El Infernal lucha a tu lado durante 4 turnos. Invocar un Infernal no sustituye ni hace desaparecer a tu demonio actual.' },
    { id: 'demonic_transformation', name: 'Demonic Transformation', icon: '👹', iconImg: 'img/capstones/warlock/demonic_transformation.jpg', description: 'Coste: 2 Soul Shards. Te transformas en un demonio durante 2 turnos, aumentando tu Spell Power un 25%, tu probabilidad de golpe crítico un 25% y tu daño crítico un 25%. Recibes un 15% más de daño.' },
    { id: 'capstone_3', name: 'Capstone III', icon: '⚡', iconImg: '', description: 'Capstone de ejemplo. (Por definir)' },
  ],

  abilities: [
    {
      id: 'shadow_bolt',
      name: 'Shadow Bolt',
      icon: '🌑',
      iconImg: 'img/abilities/warlock/Spell_Shadow_ShadowBolt.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 1,
      damageType: 'magical',
      baseDamage: 20,
      spellPowerRatio: 1.0,
      costPct: 0.08,
      castType: 'cast',
      cooldown: 0,
      description: 'Lanza una descarga de energia oscura. Genera 1 Soul Shard.',
      damageRanges: [{ rank: 1, level: 1, min: 18, max: 26 }, { rank: 2, level: 8, min: 30, max: 42 }, { rank: 3, level: 16, min: 50, max: 68 }, { rank: 4, level: 22, min: 70, max: 95 }],
      generatesShard: 1,
    },
    {
      id: 'chaos_bolt',
      name: 'Chaos Bolt',
      icon: '🔥',
      iconImg: 'img/abilities/warlock/Ability_Warlock_ChaosBolt.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 10,
      damageType: 'magical',
      baseDamage: 40,
      spellPowerRatio: 1.5,
      costPct: 0.15,
      castType: 'cast',
      cooldown: 0,
      description: 'Descarga caotica que ignora resistencias. Consume 3 Soul Shards.',
      damageRanges: [{ rank: 1, level: 10, min: 61, max: 83 }, { rank: 2, level: 18, min: 88, max: 121 }, { rank: 3, level: 24, min: 132, max: 176 }],
      spendsShards: true,
      shardCost: 3,
    },
    {
      id: 'corruption',
      name: 'Corruption',
      icon: '🟢',
      iconImg: 'img/abilities/warlock/corruption.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 4,
      damageType: 'magical',
      baseDamage: 20,
      spellPowerRatio: 0.2,
      costPct: 0.05,
      castType: 'instant',
      cooldown: 0,
      description: 'Corrompe al enemigo con un DoT de sombra durante 5 turnos. Genera 1 Soul Shard.',
      isDot: true,
      dotDuration: 5,
      damageRanges: [{ rank: 1, level: 1, min: 50, max: 50 }, { rank: 2, level: 8, min: 90, max: 90 }, { rank: 3, level: 16, min: 150, max: 150 }, { rank: 4, level: 22, min: 230, max: 230 }],
      dotRanges: [{ rank: 1, level: 4, value: 10, duration: 5 }, { rank: 2, level: 10, value: 18, duration: 5 }, { rank: 3, level: 16, value: 30, duration: 5 }, { rank: 4, level: 22, value: 46, duration: 5 }],
      generatesShard: 1,
    },
    {
      id: 'immolate',
      name: 'Immolate',
      icon: '🔥',
      iconImg: 'img/abilities/warlock/Spell_Fire_Immolation.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 6,
      damageType: 'magical',
      baseDamage: 25,
      spellPowerRatio: 0.4,
      costPct: 0.07,
      castType: 'cast',
      cooldown: 0,
      description: 'Quema al enemigo causando danyo directo y un DoT de fuego durante 3 turnos. Genera 1 Soul Shard.',
      isDot: true,
      dotDuration: 3,
      damageRanges: [{ rank: 1, level: 6, min: 20, max: 30 }, { rank: 2, level: 12, min: 35, max: 50 }, { rank: 3, level: 18, min: 55, max: 75 }, { rank: 4, level: 24, min: 85, max: 115 }],
      dotRanges: [{ rank: 1, level: 6, value: 7, duration: 3 }, { rank: 2, level: 12, value: 12, duration: 3 }, { rank: 3, level: 18, value: 18, duration: 3 }, { rank: 4, level: 24, value: 28, duration: 3 }],
      generatesShard: 1,
    },
    {
      id: 'curse_of_agony',
      name: 'Curse of Agony',
      icon: '💀',
      iconImg: 'img/abilities/warlock/Spell_Shadow_CurseOfSargeras.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 8,
      damageType: 'magical',
      baseDamage: 15,
      spellPowerRatio: 0.15,
      costPct: 0.04,
      castType: 'instant',
      cooldown: 0,
      description: 'Maldicion que causa un DoT creciente durante 6 turnos. Consume 1 Soul Shard.',
      isDot: true,
      dotDuration: 6,
      damageRanges: [{ rank: 1, level: 8, min: 66, max: 66 }, { rank: 2, level: 14, min: 121, max: 121 }, { rank: 3, level: 20, min: 198, max: 198 }, { rank: 4, level: 24, min: 286, max: 286 }],
      dotRanges: [{ rank: 1, level: 8, value: 11, duration: 6 }, { rank: 2, level: 14, value: 20, duration: 6 }, { rank: 3, level: 20, value: 33, duration: 6 }, { rank: 4, level: 24, value: 48, duration: 6 }],
      spendsShards: true,
      shardCost: 1,
    },
    {
      id: 'drain_life',
      name: 'Drain Life',
      icon: '🩸',
      iconImg: 'img/abilities/warlock/Spell_Shadow_LifeDrain02.jpg',
      school: 'Oscuro',
      type: 'damage',
      requiredLevel: 12,
      damageType: 'magical',
      baseDamage: 35,
      spellPowerRatio: 0.6,
      costPct: 0.10,
      castType: 'cast',
      cooldown: 0,
      description: 'Drena la vida del enemigo causando danyo y curandote por el 50% del danyo. Genera 1 Soul Shard.',
      damageRanges: [{ rank: 1, level: 12, min: 35, max: 50 }, { rank: 2, level: 18, min: 55, max: 75 }, { rank: 3, level: 24, min: 80, max: 110 }],
      generatesShard: 1,
      lifestealPct: 0.50,
    },
    {
      id: 'rain_of_fire',
      name: 'Rain of Fire',
      icon: '🌋',
      iconImg: 'img/abilities/warlock/Spell_Fire_FelRainOfFire.jpg',
      school: 'Fuego',
      type: 'damage',
      requiredLevel: 20,
      damageType: 'magical',
      baseDamage: 60,
      spellPowerRatio: 0.8,
      costPct: 0.20,
      castType: 'cast',
      cooldown: 0,
      description: 'Lluvia de fuego fel que danya a todos los enemigos en el area. Consume 5 Soul Shards.',
      damageRanges: [{ rank: 1, level: 20, min: 132, max: 176 }, { rank: 2, level: 24, min: 187, max: 242 }],
      aoe: true,
      spendsShards: true,
      shardCost: 5,
    },
    {
      id: 'summon_imp',
      name: 'Summon Imp',
      icon: '👹',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonImp.jpg',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 5,
      costPct: 0.15,
      castType: 'cast',
      cooldown: 0,
      description: 'Invoca un diablillo que ataca automaticamente con Firebolt cada turno.',
      isPetSummon: 'imp',
      buff: null,
    },
    {
      id: 'summon_voidwalker',
      name: 'Summon Voidwalker',
      icon: '🔵',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonVoidWalker.jpg',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 10,
      costPct: 0.25,
      castType: 'cast',
      cooldown: 0,
      description: 'Invoca un abisario tanque con mucha vida. Ataca con sombra cada turno. Consume 1 Soul Shard.',
      isPetSummon: 'voidwalker',
      buff: null,
      spendsShards: true,
      shardCost: 1,
    },
    {
      id: 'summon_succubus',
      name: 'Summon Succubus',
      icon: '💋',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonSuccubus.jpg',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 14,
      costPct: 0.30,
      castType: 'cast',
      cooldown: 0,
      description: 'Invoca una succubo que ataca con latigazos cada turno. Consume 2 Soul Shards.',
      isPetSummon: 'succubus',
      buff: null,
      spendsShards: true,
      shardCost: 2,
    },
    {
      id: 'summon_infernal',
      name: 'Summon Infernal',
      icon: '🔥',
      iconImg: 'img/capstones/warlock/sumon_infernal.jpg',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 0,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      description: 'Coste: 2 Soul Shards. Invoca un Infernal que aterriza causando daño de Fuego a todos los enemigos cercanos y aturdiendolos 1 turno. Lucha a tu lado durante 4 turnos sin sustituir a tu demonio actual.',
      buff: null,
      spendsShards: true,
      shardCost: 2,
      aoe: true,
      damageRanges: [{ rank: 1, level: 24, min: 70, max: 110 }],
      spellPowerRatio: 0.8,
      stunDuration: 1,
      infernalTurns: 4,
      infernalMin: 30,
      infernalMax: 50,
      capstoneGate: 'summon_infernal',
    },
    {
      id: 'demonic_transformation',
      name: 'Demonic Transformation',
      icon: '👹',
      iconImg: 'img/capstones/warlock/demonic_transformation.jpg',
      school: 'Demoniaco',
      type: 'utility',
      requiredLevel: 0,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      description: 'Coste: 2 Soul Shards. Te transformas en un demonio durante 2 turnos: +25% Spell Power, +25% prob. critico y +25% danyo critico. Recibes un 15% mas de danyo.',
      buff: null,
      spendsShards: true,
      shardCost: 2,
      capstoneGate: 'demonic_transformation',
    },
    {
      id: 'unsummon_pet',
      name: 'Unsummon Pet',
      icon: '👋',
      iconImg: '',
      school: 'Invocacion',
      type: 'utility',
      requiredLevel: 5,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      description: 'Desinvoca a tu pet activa.',
      buff: null,
    },
    {
      id: 'life_tap',
      name: 'Life Tap',
      icon: '💧',
      iconImg: 'img/abilities/warlock/Spell_Shadow_BurningSpirit.jpg',
      school: 'Oscuro',
      type: 'utility',
      requiredLevel: 2,
      costPct: 0,
      castType: 'instant',
      cooldown: 0,
      noGcd: true,
      description: 'Sacrifica vida para recuperar mana. No gasta accion.',
      buff: null,
      buffRanks: [{ rank: 1, level: 2, value: 40, costPct: 0 }, { rank: 2, level: 10, value: 80, costPct: 0 }, { rank: 3, level: 18, value: 140, costPct: 0 }, { rank: 4, level: 24, value: 200, costPct: 0 }],
    },
    {
      id: 'healthstone',
      name: 'Healthstone',
      icon: '💎',
      iconImg: 'img/abilities/warlock/INV_Stone_04.jpg',
      school: 'Oscuro',
      type: 'heal',
      requiredLevel: 6,
      damageType: 'magical',
      baseDamage: 30,
      spellPowerRatio: 0.5,
      costPct: 0,
      castType: 'instant',
      cooldown: 6,
      description: 'Crea una piedra de salud que cura a un aliado. Consume 1 Soul Shard.',
      damageRanges: [{ rank: 1, level: 6, min: 60, max: 80 }, { rank: 2, level: 12, min: 100, max: 130 }, { rank: 3, level: 18, min: 160, max: 200 }, { rank: 4, level: 24, min: 240, max: 300 }],
      spendsShards: true,
      shardCost: 1,
    },
    {
      id: 'fel_armor',
      name: 'Fel Armor',
      icon: '🛡️',
      iconImg: 'img/abilities/warlock/Spell_Shadow_FelArmour.jpg',
      school: 'Demoniaco',
      type: 'utility',
      requiredLevel: 10,
      costPct: 0.08,
      castType: 'instant',
      cooldown: 0,
      description: 'Armadura demoniaca que aumenta tu poder de hechizo y armadura.',
      buff: { stat: 'spellPower', duration: 30, applySelf: true, isPercent: true },
      buffRanks: [{ rank: 1, level: 10, value: 10, costPct: 0.08 }, { rank: 2, level: 18, value: 15, costPct: 0.08 }, { rank: 3, level: 24, value: 20, costPct: 0.08 }],
    },
    {
      id: 'blood_pact',
      name: 'Blood Pact',
      icon: '🩸',
      iconImg: 'img/abilities/warlock/Spell_Shadow_BloodBoil.jpg',
      school: 'Oscuro',
      type: 'utility',
      requiredLevel: 8,
      costPct: 0,
      castType: 'instant',
      cooldown: 4,
      description: 'El diablillo sacrifica sangre para dar +Aguante a todo el grupo. Cuesta mana de la pet.',
      petAbility: 'imp',
      buff: { stat: 'aguante', duration: 4, applySelf: true, isPercent: false },
      buffRanks: [{ rank: 1, level: 8, value: 5, costPct: 0 }, { rank: 2, level: 16, value: 10, costPct: 0 }, { rank: 3, level: 22, value: 15, costPct: 0 }],
      partyBuff: true,
    },
    {
      id: 'sacrificial_shield',
      name: 'Sacrificial Shield',
      icon: '🛡️',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SacrificialShield.jpg',
      school: 'Oscuro',
      type: 'utility',
      requiredLevel: 12,
      costPct: 0,
      castType: 'instant',
      cooldown: 8,
      description: 'El abisario se sacrifica, destruyendose, y otorga al brujo un escudo que absorbe danyo. Cuesta mana de la pet.',
      petAbility: 'voidwalker',
      buff: { stat: 'shield', duration: 4, applySelf: true, isPercent: false },
      buffRanks: [{ rank: 1, level: 12, value: 200, costPct: 0 }, { rank: 2, level: 18, value: 350, costPct: 0 }, { rank: 3, level: 24, value: 500, costPct: 0 }],
      destroysPet: true,
    },
    {
      id: 'shadow_kiss',
      name: 'Shadow Kiss',
      icon: '💋',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SoothingKiss.jpg',
      school: 'Oscuro',
      type: 'utility',
      requiredLevel: 16,
      costPct: 0,
      castType: 'instant',
      cooldown: 3,
      description: 'La succubo lanza un beso oscuro que causa danyo y reduce el danyo del objetivo un 15% durante 2 turnos. Cuesta mana de la pet.',
      petAbility: 'succubus',
      buff: null,
      buffRanks: [{ rank: 1, level: 16, value: 40, costPct: 0 }, { rank: 2, level: 22, value: 60, costPct: 0 }],
      inflictsEffects: [{ type: 'debuff', name: 'Seduction', stat: 'damage', value: 15, duration: 2, debuffType: 'magic' }],
    },
  ],

  pets: [
    {
      id: 'imp',
      name: 'Imp',
      icon: '👹',
      iconImg: 'img/abilities/warlock/ability_warlock_impoweredimp.jpg',
      requiredLevel: 5,
      hpPct: 0.30,
      manaPct: 0.30,
      attackName: 'Firebolt',
      attackMin: 15,
      attackMax: 25,
      attackSchool: 'Fuego',
      manaCostPct: 0.10,
    },
    {
      id: 'voidwalker',
      name: 'Voidwalker',
      icon: '🔵',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonVoidWalker.jpg',
      requiredLevel: 10,
      hpPct: 0.60,
      manaPct: 0.15,
      attackName: 'Torment',
      attackMin: 10,
      attackMax: 18,
      attackSchool: 'Oscuro',
      manaCostPct: 0.05,
    },
    {
      id: 'succubus',
      name: 'Succubus',
      icon: '💋',
      iconImg: 'img/abilities/warlock/Spell_Shadow_SummonSuccubus.jpg',
      requiredLevel: 14,
      hpPct: 0.40,
      manaPct: 0.25,
      attackName: 'Lash of Pain',
      attackMin: 20,
      attackMax: 32,
      attackSchool: 'Físico',
      manaCostPct: 0.08,
    },
  ],
};
